# Generated by Django 4.1.2 on 2022-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothrepair', '0002_question_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
