# Generated by Django 4.1.2 on 2022-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothrepair', '0003_userinfo_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceName', models.CharField(max_length=200)),
                ('priceDescrip', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=64)),
            ],
        ),
    ]
