# Generated by Django 4.1.2 on 2022-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothrepair', '0005_alter_priceinfo_pricedescrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameImg', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
